# CS110 C++ MapReduce Tools

.PHONY: directories filefree

directories:
	rm -fr files/map-output
	rm -fr files/reduce-input
	rm -fr files/output
	mkdir -p files/map-output
	mkdir -p files/reduce-input
	mkdir -p files/output

filefree:
	@rm -fr files/map-output/* files/reduce-input/* files/output/*	
